---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t sonarqube:${DRONE_COMMIT_SHA} .

- name: scan_image
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  environment:
    IMAGE_NAME: sonarqube:${DRONE_COMMIT_SHA}
    WHITELIST_FILE: cve-exceptions.txt
  when:
    event:
    - push

- name: latest_image_to_quay
  image: plugins/docker
  settings: 
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/sonarqube
    tags: latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_token
    DOCKER_USERNAME: ukhomeofficedigital+sonarqube
  when:
    branch: 
    - master
    event:
    - push 


- name: image_to_quay
  image: plugins/docker
  settings: 
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/sonarqube
    tags: ${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_token
    DOCKER_USERNAME: ukhomeofficedigital+sonarqube
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  commands:
    - /run.sh server

...
