pipeline:
  build_image:
    image: docker:18.09
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t sonarqube .

  scan_image:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    image_name: sonarqube
    fail_on_detection: false
    when:
      event: push

  image_to_quay:
    image: docker:18.09
    secrets: [docker_token]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+sonarqube" -p=$${DOCKER_TOKEN} quay.io
      - docker tag sonarqube quay.io/ukhomeofficedigital/sonarqube:latest
      - docker tag sonarqube quay.io/ukhomeofficedigital/sonarqube:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/sonarqube:latest
      - docker push quay.io/ukhomeofficedigital/sonarqube:$${DRONE_TAG}
    when:
      event: tag
