---
kind: pipeline
name: default
type: kubernetes

workspace:
  path: /drone/src

platform:
  os: linux
  arch: amd64

steps:
# - name: build_image
#   pull: if-not-exists
#   image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
#   commands:
#   - /usr/local/bin/wait
#   - docker build -t sonarqube:${DRONE_COMMIT_SHA} .

- name: build_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    - /usr/local/bin/wait
    - docker build -t sonarqube:${DRONE_COMMIT_SHA} .
    - docker save sonarqube:${DRONE_COMMIT_SHA} -o sonarqube.tar

# - name: scan_image
#   pull: always
#   image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
#   environment:
#     IMAGE_NAME: sonarqube:${DRONE_COMMIT_SHA}
#     WHITELIST_FILE: cve-exceptions.txt
#   when:
#     event:
#     - push

- name: trivy_scan
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  commands:
    - |
      set -e
      IMAGE_TAR="sonarqube.tar"

      echo "Scanning TAR image for CRITICAL vulnerabilities..."
      trivy image \
        --severity CRITICAL \
        --exit-code 1 \
        --dependency-tree \
        --input "${IMAGE_TAR}"

      echo "Scanning TAR image for HIGH/MEDIUM vulnerabilities..."
      trivy image \
        --severity HIGH,MEDIUM \
        --exit-code 0 \
        --dependency-tree \
        --input "${IMAGE_TAR}" || \
        echo "HIGH/MEDIUM vulnerabilities found (continuing)."
  when:
    event:
      include:
        - push

- name: latest_image_to_quay
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/sonarqube
    tags: latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_token
    DOCKER_USERNAME: ukhomeofficedigital+sonarqube
  when:
    branch:
    - master
    event:
    - push


- name: image_to_quay
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/sonarqube
    tags: ${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_token
    DOCKER_USERNAME: ukhomeofficedigital+sonarqube
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  commands:
    - /run.sh server

...
