pipeline:
  build_image:
    image: docker:17.07.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t sonarqube .

  scan:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    dockerfile: Dockerfile
    image_name: sonarqube
    tolerates: medium
    fail_on_detection: true
    when:
      event: push

  image_to_quay:
    image: docker:17.07.0
    secrets: [docker_token]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+sonarqube" -p=$${DOCKER_TOKEN} quay.io
      - docker tag sonarqube quay.io/ukhomeofficedigital/sonarqube:latest
      - docker tag sonarqube quay.io/ukhomeofficedigital/sonarqube:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/sonarqube:latest
      - docker push quay.io/ukhomeofficedigital/sonarqube:$${DRONE_TAG}
    when:
      event: tag
