pipeline:
  build_docker_image:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t sonarqube .
    when:
      event: push
      branch: master

  image_to_quay:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=${DOCKER_PASSWORD} quay.io
      - docker tag sonarqube quay.io/ukhomeofficedigital/sonarqube:${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/sonarqube:${DRONE_BUILD_NUMBER}
    when:
      event: push
      branch: master

  deploy_to_ops_dev:
    image: "quay.io/ukhomeofficedigital/kd:v0.2.2"
    environment:
      - KUBE_NAMESPACE=sonarqube-dev
      - "KUBE_SERVER=https://kube-hod-ops.ops.digital.homeoffice.gov.uk"
      - INSECURE_SKIP_TLS_VERIFY=true
    commands:
      - "kd --debug --insecure-skip-tls-verify --retries 30 -f kube/dev/sonarqube-dp.yaml -f kube/dev/sonarqube-svc.yaml -f kube/dev/sonarqube-ingress.yaml"
    when:
      event: push
      branch: master

  deploy_to_ops:
    image: "quay.io/ukhomeofficedigital/kd:v0.2.2"
    environment:
      - KUBE_NAMESPACE=sonarqube
      - "KUBE_SERVER=https://kube-hod-ops.ops.digital.homeoffice.gov.uk"
      - INSECURE_SKIP_TLS_VERIFY=true
    commands:
      - "kd --debug --insecure-skip-tls-verify --retries 30 -f kube/sonarqube-dp.yaml -f kube/sonarqube-svc.yaml"
    when:
      event: deployment

services:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
