version: "2"
services:
  sonarqube:
    build: .
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sonar
      MYSQL_DATABASE: sonar
      MYSQL_USER: sonar
      MYSQL_PASSWORD: sonar
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./mysql:/etc/mysql/conf.d
