apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    name: sonarqube
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 32711
    port: 80
    targetPort: 9000
  - name: https
    nodePort: 32712
    port: 443
    targetPort: 443
  selector:
    name: sonarqube
