apiVersion: v1
kind: Service
metadata:
 labels:
   name: sonarqube
 name: sonarqube
spec:
 ports:
   - name: http
     port: 80
     targetPort: 9000
   - name: https
     port: 443
     targetPort: 8889
 selector:
   name: sonarqube
