apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonarqube
  template:
    metadata:
      labels:
        name: sonarqube
        app: sonarqube
    spec:
      serviceAccount: sonarqube
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: eu-west-1b
      containers:
      - name: sonarqube
        image: quay.io/ukhomeofficedigital/sonarqube:{{.DRONE_BUILD_NUMBER}}
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
        env:
        - name: SONARQUBE_JDBC_USERNAME
          value: root
        - name: SONARQUBE_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-secrets
              key: mysql.password
        - name: SONARQUBE_JDBC_URL
          valueFrom:
            configMapKeyRef:
              name: sonarqube
              key: mysql.url
        - name: JAVA_OPTS
          value: -XX:+PrintGCDetails -XX:+UseParallelGC -Xms1G -Xmx2G
        volumeMounts:
        - mountPath: /opt/sonarqube/extensions
          name: sonarqube-data
        - name: certs
          mountPath: /etc/secrets
          readOnly: true
        # livenessProbe:
        #   exec:
        #     command:
        #       - /opt/sonarqube/bin/healthcheck.sh
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 1
        # readinessProbe:
        #   exec:
        #     command:
        #       - /opt/sonarqube/bin/healthcheck.sh
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 1
      - name: tls
        image: quay.io/ukhomeofficedigital/nginx-proxy:v1.7.0
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        - containerPort: 80
        env:
        - name: PROXY_SERVICE_HOST
          value: 127.0.0.1
        - name: PROXY_SERVICE_PORT
          value: "9000"
        - name: ENABLE_UUID_PARAM
          value: "FALSE"
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        - name: ERROR_REDIRECT_CODES
          value: "599"
        # - name: HTTPS_REDIRECT
        #   value: "FALSE"
        - name: CLIENT_MAX_BODY_SIZE
          value: "0"
        - name: ADD_NGINX_SERVER_CFG
          value: |
            add_header Cache-Control private;
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header X-Forwarded-Proto "https";
        - name: SSL_CERT
          value: /etc/secrets/tls-bundle.pem
        - name: SSL_KEY
          value: /etc/secrets/tls-key.pem
        volumeMounts:
          - name: certs
            mountPath: /etc/secrets
            readOnly: true
      - name: vault-side-kick
        image: quay.io/ukhomeofficedigital/vault-sidekick-jks:v0.2.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "100Mi"
            cpu: 100m
          requests:
            memory: "50Mi"
            cpu: 100m
        args:
          - -output=/etc/secrets
          - -tls-skip-verify=true
          - -cn=pki:services/${NAMESPACE}/pki/issue/default:common_name=sonarqube.${NAMESPACE}.svc.cluster.local,file=/etc/keystore/admin,fmt=cert,exec=/usr/bin/create-keystore.sh
        env:
          - name: VAULT_ADDR
            value: "https://vault.vault.svc.cluster.local:8200"
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: store-token
                key: token
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - mountPath: /etc/keystore
            name: certs
      volumes:
        - name: certs
          emptyDir: {}
        - name: sonarqube-data
          awsElasticBlockStore:
            volumeID: vol-a7832025
            fsType: ext4
