apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonarqube
  template:
    metadata:
      labels:
        name: sonarqube
        app: sonarqube
    spec:
      serviceAccount: sonarqube
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: eu-west-1b
      containers:
      - name: sonarqube
        image: quay.io/ukhomeofficedigital/sonarqube:{{.DRONE_BUILD_NUMBER}}
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
          # - -Dsonar.web.port=-1
        ports:
        - containerPort: 443
        - containerPort: 9000
        env:
        - name: SONARQUBE_OPTS
          value: "-Dsonar.web.javaOpts=-server -Dsonar.web.https.port=443 -Dsonar.web.https.keyAlias=cert -Dsonar.web.https.keystoreFile=/etc/secrets/keystore.jks"
        - name: SONARQUBE_JDBC_USERNAME
          value: root
        - name: SONARQUBE_JDBC_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sonarqube
              key: mysql.password
        - name: SONARQUBE_JDBC_URL
          valueFrom:
            configMapKeyRef:
              name: sonarqube
              key: mysql.url
        - name: JAVA_OPTS
          value: -XX:+PrintGCDetails -XX:+UseParallelGC -Xms1G -Xmx2G
        volumeMounts:
        - mountPath: /opt/sonarqube/extensions
          name: sonarqube-data
        - name: certs
          mountPath: /etc/secrets
          readOnly: true
        # livenessProbe:
        #   exec:
        #     command:
        #       - /opt/sonarqube/bin/healthcheck.sh
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 1
        # readinessProbe:
        #   exec:
        #     command:
        #       - /opt/sonarqube/bin/healthcheck.sh
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 1
      - name: vault-side-kick
        image: quay.io/ukhomeofficedigital/vault-sidekick-jks:v0.2.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "100Mi"
            cpu: 100m
          requests:
            memory: "50Mi"
            cpu: 100m
        args:
          - -output=/etc/secrets
          - -tls-skip-verify=true
          - -cn=pki:services/${NAMESPACE}/pki/issue/default:common_name=sonarqube.${NAMESPACE}.svc.cluster.local,file=/etc/keystore/admin,fmt=cert,exec=/usr/bin/create-keystore.sh
        env:
          - name: VAULT_ADDR
            value: "https://vault.vault.svc.cluster.local:8200"
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: store-token
                key: token
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - mountPath: /etc/keystore
            name: certs
      volumes:
        - name: certs
          emptyDir: {}
        - name: sonarqube-data
          awsElasticBlockStore:
            volumeID: vol-a7832025
            fsType: ext4
