apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-sonar-props
  namespace: sonarqube-dev
data:
  sonar.properties: |
    sonar.authenticator.createUsers=true
    sonar.security.realm=keycloak
    sonar.keycloak.json={"realm": "master", "auth-server-url": "https://sso-dev.notprod.homeoffice.gov.uk/auth", "ssl-required": "external", "resource": "sonarqube-dev-realm", "credentials": {"secret": "f4903dd8-9cf9-48fb-bfcb-916a9dc7232a"}}
